import "../styles/index.scss";
import Footer from "./components/footer";
import Header from "./components/header";
import ReduxProvider from "./store/ReduxProvider";
import { ModalProvider } from "./context/accountLinkProvider";
import { SurebankerToggleProvider } from "./context/surebankerToogleModal";
import { SurebankerToggleSuccessProvider } from "./context/surebankerToggleSuccessModal";
import { TierLevelCompletionProvider } from "./context/tierLevelCompletionProvider";
import { Toast } from "./toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider> 
          <ModalProvider>
            <SurebankerToggleProvider>
              <SurebankerToggleSuccessProvider>
                <TierLevelCompletionProvider>
                  {/* <Header /> */}
                  {children}
                  {/* <Footer /> */}
                  <Toast />
                </TierLevelCompletionProvider>
              </SurebankerToggleSuccessProvider>
            </SurebankerToggleProvider>
          </ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
